Add a better error message for when turbopack cannot be loaded (#89633)
Add a more direct error message when next is running on a platform that turbopack doesn't support

document supported turbopack platforms

## Testing

To test i just set `NEXT_TEST_WASM=1` and ran a build

```
Error: Turbopack is not supported on this platform (darwin/arm64) because native bindings are not available. Only WebAssembly (WASM) bindings were loaded, and Turbopack requires native bindings.

To use Next.js on this platform, use Webpack instead:
  next dev --webpack

For more information, see: https://nextjs.org/docs/app/api-reference/turbopack#supported-platforms
    at ignore-listed frames

```
so it should work.  Messaging probably could be better (there is also a messge about not being able to set the lockfile) but this should be much better

Fixes #89305